version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    depends_on: [db]
    ports: ["8000:8000"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports: ["5173:80"]
    environment:
      - VITE_API_BASE=http://localhost:8000

volumes:
  dbdata:
